### ISSUE TITLE
Cannot start rviz

### ISSUE THREAD

**Issue by Iwtbm** [masszhou/ros-docker#1]
I follow your instructions but I cannot start rviz in the new terminal.
The error is like this:
...
libGL error: failed to load driver: swrast
libGL error: failed to load driver: swrast
rviz::RenderSystem: error creating render window: std::exception
...

Could you help me ?

**Comment by masszhou** [comment]
Hi,
I can repeat your problem.
after some experiments, I guess it could be invoked by nvidia-docker2, since this image was build and used with nvidia-docker.
I would suggest you use the maintained  nvidia ros docker image directly.
https://github.com/ros-industrial/docker

I create this image many years ago, when there is no gpu supported ros images.
Now this image is out-dated, and nvidia-docker2 was also released.
This image is not maintained anymore.

Hope this can help you.

**Comment by Iwtbm** [comment]
> Hi,
> I can repeat your problem.
> after some experiments, I guess it could be invoked by nvidia-docker2, since this image was build and used with nvidia-docker.
> I would suggest you use the maintained nvidia ros docker image directly.
> https://github.com/ros-industrial/docker
> 
> I create this image many years ago, when there is no gpu supported ros images.
> Now this image is out-dated, and nvidia-docker2 was also released.
> This image is not maintained anymore.
> 
> Hope this can help you.

Hi, I did not use nvidia-docker. So, I must use NVIDIA docker to use rviz even I dont have nvidia driver?
